import { StrictMode, useEffect, useState, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';
import './styles.css';

type User = { name: string; email: string; role: string };
const roleLabels: Record<string, string> = { SUPER_ADMIN: 'Super Admin', CURATOR: 'Kurator', OPERATIONS: 'Operasional', PARTNER: 'Mitra', CUSTOMER: 'Pelanggan', NAZHIR_VIEWER: 'Nazhir Viewer' };
const API_BASE_URL = (import.meta.env.VITE_API_URL ?? '').replace(/\/$/, '');
const apiUrl = (path: string) => `${API_BASE_URL}${path}`;

export function App() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [user, setUser] = useState<User | null>(null); const [error, setError] = useState(''); const [sessionError, setSessionError] = useState(''); const [busy, setBusy] = useState(false); const [loadingSession, setLoadingSession] = useState(true);
  useEffect(() => { let active = true; fetch(apiUrl('/auth/me'), { credentials: 'include' }).then(async (response) => { if (response.status === 401) return null; if (!response.ok) throw new Error('Sesi tidak dapat diperiksa'); const data = await response.json(); return data.user as User; }).then((currentUser) => { if (active) setUser(currentUser); }).catch(() => { if (active) setSessionError('Sesi tidak dapat diperiksa. Coba lagi.'); }).finally(() => { if (active) setLoadingSession(false); }); return () => { active = false; }; }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setBusy(true); try { const response = await fetch(apiUrl('/auth/login'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Login gagal'); setUser(data.user); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Login gagal'); } finally { setBusy(false); } }
  async function logout() { try { const response = await fetch(apiUrl('/auth/logout'), { method: 'POST', credentials: 'include' }); if (!response.ok) throw new Error('Logout gagal'); setUser(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Logout gagal'); } }
  return <main className="shell"><section className="intro"><div className="brand"><span className="brand-mark"><Sparkles size={18} /></span><span>dapuremakita</span></div><div className="intro-copy"><p className="eyebrow">Ruang kerja kurasi</p><h1>Produk pilihan,<br /><em>cerita yang berarti.</em></h1><p className="lede">Satu ruang tenang untuk mengelola perjalanan produk lokal dari dapur hingga pelanggan.</p></div><div className="signal"><ShieldCheck size={18} /><span>Platform aman untuk setiap peran</span></div></section><section className="panel">{loadingSession ? <div className="welcome" role="status"><p className="eyebrow">Tunggu sebentar</p><h2>Memeriksa sesi...</h2></div> : sessionError ? <div className="welcome"><p className="error" role="alert">{sessionError}</p><button className="primary" onClick={() => window.location.reload()}>Coba lagi <ArrowRight size={17} /></button></div> : user ? <div className="welcome"><div className="avatar">{user.name[0]}</div><p className="eyebrow">Selamat datang kembali</p><h2>{user.name}</h2><p className="muted">{roleLabels[user.role] ?? user.role} · {user.email}</p><button className="primary" onClick={logout}>Keluar <ArrowRight size={17} /></button>{error && <p className="error" role="alert">{error}</p>}</div> : <form onSubmit={submit}><div className="panel-heading"><p className="eyebrow">Akses akun</p><h2>Masuk ke ruang kerja</h2><p className="muted">Gunakan akun yang sudah terdaftar untuk melanjutkan.</p></div><label>Email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="nama@contoh.id" /></label><label>Kata sandi<input type="password" required value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Masukkan kata sandi" /></label>{error && <p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Memeriksa...' : 'Masuk'} <ArrowRight size={17} /></button><p className="secure"><LockKeyhole size={15} /> Sesi dilindungi dengan koneksi aman</p></form>}</section></main>;
}
const root = document.getElementById('root');
if (root) createRoot(root).render(<StrictMode><App /></StrictMode>);
