import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, Check, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';

export type CartItem = { productId: string; slug: string; name: string; price: number; quantity: number };
const CART_KEY = 'dapuremakita.cart.v1';
export const readCart = (): CartItem[] => { try { return JSON.parse(localStorage.getItem(CART_KEY) ?? '[]') as CartItem[]; } catch { return []; } };
export const cartTotal = (items: CartItem[]) => items.reduce((total, item) => total + item.price * item.quantity, 0);
export const saveCart = (items: CartItem[]) => localStorage.setItem(CART_KEY, JSON.stringify(items.filter((item) => item.quantity > 0)));
export const addCartItem = (item: Omit<CartItem, 'quantity'>) => { const items = readCart(); const existing = items.find((current) => current.productId === item.productId); saveCart(existing ? items.map((current) => current.productId === item.productId ? { ...current, quantity: current.quantity + 1 } : current) : [...items, { ...item, quantity: 1 }]); };
const money = (value: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);
const API = (import.meta.env.VITE_API_URL ?? '').replace(/\/$/, '');
const request = async (path: string, init?: RequestInit) => { const response = await fetch(`${API}${path}`, { credentials: 'include', ...init }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? 'Permintaan belum berhasil.'); return data; };
const navigate = (path: string) => { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); };

function CartRows({ items, setItems }: { items: CartItem[]; setItems: (items: CartItem[]) => void }) { const update = (id: string, quantity: number) => { const next = items.map((item) => item.productId === id ? { ...item, quantity } : item).filter((item) => item.quantity > 0); saveCart(next); setItems(next); }; return <div className="order-items">{items.map((item) => <div className="order-item" key={item.productId}><div><strong>{item.name}</strong><small>{money(item.price)} per item</small></div><div className="quantity"><button type="button" aria-label={`Kurangi ${item.name}`} onClick={() => update(item.productId, item.quantity - 1)}><Minus size={15} /></button><span>{item.quantity}</span><button type="button" aria-label={`Tambah ${item.name}`} onClick={() => update(item.productId, item.quantity + 1)}><Plus size={15} /></button></div><strong>{money(item.price * item.quantity)}</strong><button type="button" aria-label={`Hapus ${item.name}`} className="icon-button" onClick={() => update(item.productId, 0)}><Trash2 size={16} /></button></div>)}</div>; }

export function CartPage() { const [items, setItems] = useState<CartItem[]>(() => readCart()); if (!items.length) return <main className="section order-page"><p className="eyebrow">Keranjang</p><h1>Keranjang masih kosong.</h1><button className="button primary" onClick={() => navigate('/katalog')}>Jelajahi katalog</button></main>; return <main className="section order-page"><button className="back-link" onClick={() => navigate('/katalog')}><ArrowLeft size={16} /> Kembali ke katalog</button><div className="order-heading"><div><p className="eyebrow">Keranjang Anda</p><h1>Siap dikirim<br /><em>untuk Anda.</em></h1></div><ShoppingBag size={42} /></div><CartRows items={items} setItems={setItems} /><div className="order-total"><span>Total</span><strong>{money(cartTotal(items))}</strong></div><button className="button primary" onClick={() => navigate('/checkout')}>Lanjut ke checkout</button><button className="text-link clear-cart" onClick={() => { saveCart([]); setItems([]); }}>Kosongkan keranjang</button></main>; }

type CheckoutForm = { name: string; email: string; phone: string; address: string; city: string; province: string; postalCode: string };
export function CheckoutPage() { const [items] = useState<CartItem[]>(() => readCart()); const [form, setForm] = useState<CheckoutForm>({ name: '', email: '', phone: '', address: '', city: '', province: '', postalCode: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); if (!items.length) return <main className="section order-page"><h1>Keranjang kosong.</h1><button className="button primary" onClick={() => navigate('/katalog')}>Kembali ke katalog</button></main>; const change = (field: keyof CheckoutForm, value: string) => setForm({ ...form, [field]: value }); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const idempotencyKey = `checkout-${crypto.randomUUID()}`; const result = await request('/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: window.location.origin }, body: JSON.stringify({ idempotencyKey, customer: { name: form.name, email: form.email, phone: form.phone }, shipping: { address: form.address, city: form.city, province: form.province, postalCode: form.postalCode }, items: items.map((item) => ({ productId: item.productId, quantity: item.quantity })) }) }); saveCart([]); navigate(`/checkout/${result.order.orderNumber}/bayar`); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } } return <main className="section order-page"><button className="back-link" onClick={() => navigate('/cart')}><ArrowLeft size={16} /> Kembali ke keranjang</button><div className="checkout-grid"><form className="portal-form" onSubmit={submit}><p className="eyebrow">Checkout tamu</p><h1>Ke mana pesanan<br /><em>ini berjalan?</em></h1><div className="form-grid">{([['name', 'Nama lengkap'], ['email', 'Email'], ['phone', 'Nomor telepon'], ['address', 'Alamat pengiriman'], ['city', 'Kota'], ['province', 'Provinsi'], ['postalCode', 'Kode pos']] as const).map(([field, label]) => <label key={field} className={field === 'address' ? 'wide' : ''}>{label}<input required type={field === 'email' ? 'email' : 'text'} value={form[field]} onChange={(event) => change(field, event.target.value)} /></label>)}</div>{error && <p className="error-box" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy ? 'Memproses...' : 'Lanjut ke pembayaran'}</button></form><aside className="order-summary"><p className="eyebrow">Ringkasan</p>{items.map((item) => <div className="summary-row" key={item.productId}><span>{item.name} x {item.quantity}</span><strong>{money(item.price * item.quantity)}</strong></div>)}<div className="order-total"><span>Total</span><strong>{money(cartTotal(items))}</strong></div></aside></div></main>; }

export function PaymentPage({ orderNumber }: { orderNumber: string }) { const [state, setState] = useState<'ready' | 'success' | 'failure'>('ready'); const [error, setError] = useState(''); async function pay(outcome: 'success' | 'failure') { setError(''); try { await request(`/orders/${orderNumber}/payment`, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: window.location.origin }, body: JSON.stringify({ idempotencyKey: `payment-${orderNumber}`, outcome }) }); setState(outcome === 'success' ? 'success' : 'failure'); } catch (reason) { setError((reason as Error).message); } } if (state === 'success') return <main className="section order-page success-page"><Check size={48} /><p className="eyebrow">Pembayaran berhasil</p><h1>Terima kasih,<br /><em>pesanan tercatat.</em></h1><p>Nomor pesanan Anda: <strong>{orderNumber}</strong></p><button className="button primary" onClick={() => navigate(`/order/${orderNumber}`)}>Lihat status pesanan</button></main>; return <main className="section order-page"><p className="eyebrow">Pembayaran mock</p><h1>Pilih hasil<br /><em>pembayaran.</em></h1><p className="lede">Gunakan simulasi ini untuk menguji alur pesanan tanpa transaksi nyata.</p>{error && <p className="error-box" role="alert">{error}</p>}{state === 'failure' && <p className="error-box" role="alert">Pembayaran gagal. Pesanan belum dibayar.</p>}<div className="actions"><button className="button primary" onClick={() => pay('success')}>Bayar berhasil</button><button className="button light" onClick={() => pay('failure')}>Simulasikan gagal</button></div></main>; }

export function OrderStatusPage({ orderNumber }: { orderNumber: string }) { const [order, setOrder] = useState<any>(null); const [error, setError] = useState(''); useEffect(() => { request(`/orders/${orderNumber}`).then((data) => setOrder(data.order)).catch((reason) => setError((reason as Error).message)); }, [orderNumber]); if (error) return <main className="state page-state error-box" role="alert">{error}</main>; if (!order) return <main className="state page-state" role="status">Memuat status pesanan...</main>; return <main className="section order-page"><p className="eyebrow">Status pesanan {order.orderNumber}</p><h1>{order.status}</h1><p className="lede">Total {money(order.totalRupiah)} · {order.customerName}</p><div className="timeline">{order.statusHistory.map((history: any) => <div className="timeline-item" key={history.id}><strong>{history.toStatus}</strong><span>{new Date(history.createdAt).toLocaleString('id-ID')}</span></div>)}</div></main>; }

export function AdminOrders() { const [orders, setOrders] = useState<any[]>([]); useEffect(() => { request('/api/admin/orders').then((data) => setOrders(data.orders)).catch(() => setOrders([])); }, []); return <Shell title="Pesanan masuk"><div className="order-list">{orders.map((order) => <button className="order-list-row" key={order.id} onClick={() => navigate(`/admin/orders/${order.id}`)}><span>{order.orderNumber}</span><strong>{order.status}</strong><span>{money(order.totalRupiah)}</span></button>)}</div></Shell>; }
export function PartnerOrders() { const [items, setItems] = useState<any[]>([]); useEffect(() => { request('/api/partner/orders').then((data) => setItems(data.items)).catch(() => setItems([])); }, []); return <Shell title="Pesanan untuk diproduksi"><div className="order-list">{items.map((item) => <div className="order-list-row" key={item.id}><span>{item.productNameSnapshot} x {item.quantity}</span><strong>{item.productionStatus}</strong><span>{item.order.orderNumber}</span></div>)}</div></Shell>; }
function Shell({ title, children }: { title: string; children: React.ReactNode }) { return <div className="portal-shell"><header className="portal-header"><button className="brand" onClick={() => navigate('/')}>dapuremakita</button><button className="text-link" onClick={() => navigate('/login')}>Keluar</button></header><main className="portal-main"><div className="portal-heading"><p className="eyebrow">Ruang kerja</p><h1>{title}</h1></div>{children}</main></div>; }
