import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { FileText, LayoutDashboard, LogOut, Menu, PackagePlus, UserRound, X } from 'lucide-react';

const API = import.meta.env.VITE_API_URL ?? '';
let sessionUser: { name: string; role: string } | null = null;
export const setPortalSessionUser = (user: { name: string; role: string }) => { sessionUser = user; };
const request = async (path: string, init?: RequestInit) => {
  const response = await fetch(`${API}${path}`, { credentials: 'include', ...init });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error ?? 'Permintaan belum berhasil.');
  return data;
};
const navigate = (path: string) => { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); };
const statusLabel: Record<string, string> = { DRAFT: 'Draft', SUBMITTED: 'Dikirim', IN_REVIEW: 'Sedang ditinjau', REVISION_REQUIRED: 'Perlu revisi', APPROVED: 'Disetujui', REJECTED: 'Ditolak' };
const money = (value: number | null) => value === null ? '-' : new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);

type Profile = { contactName: string; phone: string; address: string; city: string; province: string; postalCode: string };
type Submission = { id: string; name: string; description: string; categoryId: string; hppRupiah: number | null; capacityAmount: number | null; capacityUnit: string | null; capacityPeriod: string | null; status: string; updatedAt: string; photos?: { id: string; originalName: string }[]; revisions?: { id: string; note?: string; toStatus: string; createdAt: string; actor: { name: string } }[] };

function Loading() { return <div className="portal-state" role="status">Memuat data portal...</div>; }
function ErrorState({ message }: { message: string }) { return <div className="portal-state error-box" role="alert">{message}</div>; }
function Shell({ title, children }: { title: string; children: ReactNode }) {
  const [open, setOpen] = useState(false);
  const links = [['/portal/mitra', 'Dashboard', LayoutDashboard], ['/portal/mitra/profil', 'Profil', UserRound], ['/portal/mitra/legalitas', 'Legalitas', FileText], ['/portal/mitra/pengajuan', 'Pengajuan', PackagePlus]] as const;
  async function logout() { await request('/auth/logout', { method: 'POST', headers: { Origin: window.location.origin } }); navigate('/login'); }
  return <div className="portal-shell"><header className="portal-header"><a className="brand" href="/" onClick={(event) => { event.preventDefault(); navigate('/'); }}>dapuremakita</a><button className="menu-button" aria-label={open ? 'Tutup navigasi portal' : 'Buka navigasi portal'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><nav className={`portal-nav ${open ? 'open' : ''}`} aria-label="Navigasi portal">{links.map(([href, label, Icon]) => <a key={href} className={window.location.pathname === href ? 'active' : ''} href={href} onClick={(event) => { event.preventDefault(); setOpen(false); navigate(href); }}><Icon size={17} />{label}</a>)}<button onClick={logout}><LogOut size={17} />Keluar</button></nav></header><main className="portal-main"><div className="portal-heading"><p className="eyebrow">Portal mitra</p><h1>{title}{sessionUser ? ` - ${sessionUser.name}` : ''}</h1></div>{children}</main></div>;
}
function Guard({ children }: { children: ReactNode }) {
  const [state, setState] = useState<'loading' | 'ready' | 'forbidden' | 'error'>('loading');
  useEffect(() => { request('/auth/me').then((data) => { sessionUser = data.user; setState(data.user.role === 'PARTNER' ? 'ready' : 'forbidden'); }).catch((error) => { if (error.message.includes('Authentication')) navigate('/login'); else if (sessionUser?.role === 'PARTNER') setState('ready'); else setState('error'); }); }, []);
  if (state === 'loading') return <Loading />;
  if (state === 'forbidden') return <ErrorState message="Portal ini hanya tersedia untuk akun mitra." />;
  if (state === 'error') return <ErrorState message="Sesi belum dapat diperiksa." />;
  return <>{children}</>;
}
function Dashboard() {
  const [data, setData] = useState<{ partner: { name: string }; counts: Record<string, number | string> } | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { request('/api/partner/overview').then(setData).catch((e) => setError(e.message)); }, []);
  if (error) return <ErrorState message={error} />;
  if (!data) return <Loading />;
  return <><section className="portal-welcome"><div><p className="eyebrow">Ruang kerja Anda</p><h2>{data.partner.name}</h2><p>Kelola profil, legalitas, dan pengajuan produk dari satu tempat.</p></div><a className="button primary" href="/portal/mitra/pengajuan/new" onClick={(e) => { e.preventDefault(); navigate('/portal/mitra/pengajuan/new'); }}>Ajukan produk</a></section><section className="metric-grid" aria-label="Ringkasan portal">{[['Draft', data.counts.drafts], ['Pengajuan aktif', data.counts.submitted], ['Dokumen', data.counts.documents], ['Profil', data.counts.profile ? 'Lengkap' : 'Belum']].map(([label, value]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section></>;
}
function ProfilePage() {
  const empty: Profile = { contactName: '', phone: '', address: '', city: '', province: '', postalCode: '' };
  const [profile, setProfile] = useState<Profile>(empty); const [state, setState] = useState('loading'); const [message, setMessage] = useState('');
  useEffect(() => { request('/api/partner/profile').then((data) => { if (data.profile) setProfile(data.profile); setState('ready'); }).catch((e) => { setMessage(e.message); setState('error'); }); }, []);
  async function save(event: FormEvent) { event.preventDefault(); try { await request('/api/partner/profile', { method: 'PUT', headers: { 'Content-Type': 'application/json', Origin: window.location.origin }, body: JSON.stringify(profile) }); setMessage('Profil berhasil disimpan.'); } catch (e) { setMessage((e as Error).message); } }
  if (state === 'loading') return <Loading />; if (state === 'error') return <ErrorState message={message} />;
  const labels: Record<keyof Profile, string> = { contactName: 'Nama kontak', phone: 'Nomor telepon', address: 'Alamat', city: 'Kota', province: 'Provinsi', postalCode: 'Kode pos' };
  return <form className="portal-form" onSubmit={save}><div className="form-grid">{(Object.keys(labels) as (keyof Profile)[]).map((field) => <label key={field}>{labels[field]}<input required value={profile[field]} onChange={(e) => setProfile({ ...profile, [field]: e.target.value })} /></label>)}</div>{message && <p role="status">{message}</p>}<button className="button primary">Simpan profil</button></form>;
}
function LegalPage() {
  const [documents, setDocuments] = useState<Array<{ id: string; originalName: string; type: string; status: string }>>([]); const [file, setFile] = useState<File | null>(null); const [type, setType] = useState('BUSINESS_LICENSE'); const [state, setState] = useState('loading'); const [message, setMessage] = useState('');
  const load = () => { void request('/api/partner/legal-documents').then((data) => { setDocuments(data.documents); setState('ready'); }).catch((e) => { setMessage(e.message); setState('error'); }); }; useEffect(() => { load(); }, []);
  async function upload(event: FormEvent) { event.preventDefault(); const selected = file ?? (event.currentTarget as HTMLFormElement).querySelector<HTMLInputElement>('input[type="file"]')?.files?.[0]; if (!selected) return; const body = new FormData(); body.append('type', type); body.append('file', selected); try { await request('/api/partner/legal-documents', { method: 'POST', headers: { Origin: window.location.origin }, body }); setFile(null); setMessage('Dokumen berhasil diunggah.'); load(); } catch (e) { setMessage((e as Error).message); } }
  async function remove(id: string) { await request(`/api/partner/legal-documents/${id}`, { method: 'DELETE', headers: { Origin: window.location.origin } }); load(); }
  if (state === 'loading') return <Loading />; if (state === 'error') return <ErrorState message={message} />;
  return <><form className="portal-form inline-form" onSubmit={upload}><label>Jenis dokumen<select value={type} onChange={(e) => setType(e.target.value)}><option value="BUSINESS_LICENSE">Legalitas usaha</option><option value="IDENTITY">Identitas</option><option value="FOOD_SAFETY">Keamanan pangan</option><option value="OTHER">Lainnya</option></select></label><label>File PDF/JPEG/PNG<input required type="file" accept="application/pdf,image/jpeg,image/png" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label><button className="button primary">Upload</button></form>{message && <p role="status">{message}</p>}<section className="list-panel"><h2>Dokumen tersimpan</h2>{documents.length === 0 ? <p className="empty-state">Belum ada dokumen legalitas.</p> : documents.map((document) => <div className="list-row" key={document.id}><FileText size={20} /><span><strong>{document.originalName}</strong><small>{document.type} · {document.status}</small></span><button className="text-link" type="button" onClick={() => remove(document.id)}>Hapus</button></div>)}</section></>;
}
function SubmissionForm({ existing }: { existing?: Submission }) {
  const [form, setForm] = useState({ name: existing?.name ?? '', description: existing?.description ?? '', categoryId: existing?.categoryId ?? '', hppRupiah: existing?.hppRupiah?.toString() ?? '', capacityAmount: existing?.capacityAmount?.toString() ?? '', capacityUnit: existing?.capacityUnit ?? '', capacityPeriod: existing?.capacityPeriod ?? '' }); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(''); const [categories, setCategories] = useState<Array<{ id: string; name: string; slug: string }>>([]);
  useEffect(() => { request('/api/partner/categories').then((data) => setCategories(data.categories)).catch(() => setCategories([])); }, []);
  async function save(event: FormEvent, submit = false) { event.preventDefault(); setMessage(''); const payload = { ...form, hppRupiah: form.hppRupiah ? Number(form.hppRupiah) : null, capacityAmount: form.capacityAmount ? Number(form.capacityAmount) : null }; try { const data = existing ? await request(`/api/partner/submissions/${existing.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Origin: window.location.origin }, body: JSON.stringify(payload) }) : await request('/api/partner/submissions', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: window.location.origin }, body: JSON.stringify(payload) }); const id = existing?.id ?? data.submission.id; if (file) { const body = new FormData(); body.append('file', file); await request(`/api/partner/submissions/${id}/photos`, { method: 'POST', headers: { Origin: window.location.origin }, body }); } if (submit) await request(`/api/partner/submissions/${id}/submit`, { method: 'POST', headers: { Origin: window.location.origin } }); navigate(`/portal/mitra/pengajuan/${id}`); } catch (e) { setMessage((e as Error).message); } }
  return <form className="portal-form" onSubmit={save}><div className="form-grid"><label>Nama produk<input required minLength={2} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Kategori<select required value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })}><option value="">Pilih kategori</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="wide">Deskripsi<textarea required minLength={10} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>HPP (rupiah)<input type="number" min="1" step="1" inputMode="numeric" value={form.hppRupiah} onChange={(e) => setForm({ ...form, hppRupiah: e.target.value.replace(/[^0-9]/g, '') })} /></label><label>Kapasitas per periode<input type="number" min="1" step="1" inputMode="numeric" value={form.capacityAmount} onChange={(e) => setForm({ ...form, capacityAmount: e.target.value.replace(/[^0-9]/g, '') })} /></label><label>Unit kapasitas<input value={form.capacityUnit} onChange={(e) => setForm({ ...form, capacityUnit: e.target.value })} /></label><label>Periode<input value={form.capacityPeriod} onChange={(e) => setForm({ ...form, capacityPeriod: e.target.value })} /></label><label className="wide">Foto awal<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label></div>{message && <p className="error-box" role="alert">{message}</p>}<div className="form-actions"><button className="button light">Simpan draft</button><button className="button primary" type="button" onClick={(e) => save(e, true)}>Simpan dan kirim</button></div></form>;
}
function SubmissionsPage() { const [items, setItems] = useState<Submission[] | null>(null); const [error, setError] = useState(''); useEffect(() => { request('/api/partner/submissions').then((data) => setItems(data.submissions)).catch((e) => setError(e.message)); }, []); if (error) return <ErrorState message={error} />; if (!items) return <Loading />; return <><div className="section-heading"><h2>Pengajuan produk</h2><a className="button primary" href="/portal/mitra/pengajuan/new" onClick={(e) => { e.preventDefault(); navigate('/portal/mitra/pengajuan/new'); }}>Pengajuan baru</a></div>{items.length === 0 ? <p className="empty-state">Belum ada pengajuan. Mulai dari draft pertama Anda.</p> : <div className="submission-list">{items.map((item) => <a className="submission-card" key={item.id} href={`/portal/mitra/pengajuan/${item.id}`} onClick={(e) => { e.preventDefault(); navigate(`/portal/mitra/pengajuan/${item.id}`); }}><span className={`status-badge ${item.status.toLowerCase()}`}>{statusLabel[item.status]}</span><h3>{item.name}</h3><p>Diperbarui {new Date(item.updatedAt).toLocaleDateString('id-ID')}</p></a>)}</div>}</>; }
function SubmissionDetail({ id }: { id: string }) { const [item, setItem] = useState<Submission | null>(null); const [error, setError] = useState(''); useEffect(() => { request(`/api/partner/submissions/${id}`).then((data) => setItem(data.submission)).catch((e) => setError(e.message)); }, [id]); if (error) return <ErrorState message={error} />; if (!item) return <Loading />; const editable = item.status === 'DRAFT' || item.status === 'REVISION_REQUIRED'; return <><div className="detail-panel"><span className={`status-badge ${item.status.toLowerCase()}`}>{statusLabel[item.status]}</span><h2>{item.name}</h2><p>{item.description}</p><dl><dt>HPP</dt><dd>{money(item.hppRupiah)}</dd><dt>Kapasitas</dt><dd>{item.capacityAmount ?? '-'} {item.capacityUnit ?? ''} {item.capacityPeriod ?? ''}</dd></dl>{editable && <a className="button primary" href={`/portal/mitra/pengajuan/${id}/edit`} onClick={(e) => { e.preventDefault(); navigate(`/portal/mitra/pengajuan/${id}/edit`); }}>Edit pengajuan</a>}</div><section className="timeline"><h2>Riwayat status</h2>{item.revisions?.length ? item.revisions.map((revision) => <div className="timeline-item" key={revision.id}><strong>{statusLabel[revision.toStatus]}</strong><span>{revision.actor.name} · {new Date(revision.createdAt).toLocaleDateString('id-ID')}</span>{revision.note && <p>{revision.note}</p>}</div>) : <p>Belum ada riwayat perubahan.</p>}</section></>; }
function SubmissionEdit({ id }: { id: string }) { const [item, setItem] = useState<Submission | null>(null); const [error, setError] = useState(''); useEffect(() => { request(`/api/partner/submissions/${id}`).then((data) => setItem(data.submission)).catch((e) => setError(e.message)); }, [id]); if (error) return <ErrorState message={error} />; return item ? <SubmissionForm existing={item} /> : <Loading />; }
export function Portal({ path }: { path: string }) { const parts = path.split('/').filter(Boolean); const area = parts[2]; const title = area === 'profil' ? 'Profil mitra' : area === 'legalitas' ? 'Dokumen legalitas' : area === 'pengajuan' ? (parts[3] === 'new' ? 'Pengajuan produk baru' : parts[4] === 'edit' ? 'Revisi pengajuan' : parts[3] ? 'Detail pengajuan' : 'Pengajuan produk') : 'Dashboard mitra'; let content: ReactNode = <Dashboard />; if (area === 'profil') content = <ProfilePage />; else if (area === 'legalitas') content = <LegalPage />; else if (area === 'pengajuan' && parts[3] === 'new') content = <SubmissionForm />; else if (area === 'pengajuan' && parts[3] && parts[4] === 'edit') content = <SubmissionEdit id={parts[3]} />; else if (area === 'pengajuan' && parts[3]) content = <SubmissionDetail id={parts[3]} />; else if (area === 'pengajuan') content = <SubmissionsPage />; return <Guard><Shell title={title}>{content}</Shell></Guard>; }
