import { Router } from 'express';
import multer from 'multer';
import path from 'node:path';
import { readFile } from 'node:fs/promises';
import { z } from 'zod';
import { LegalDocumentType, PrismaClient, SubmissionStatus } from '@prisma/client';
import type { AuthService } from '../services/auth.js';
import { authenticate, requireRoles, requireSameOrigin } from '../middleware/auth.js';
import { HttpError } from '../middleware/errors.js';
import { absoluteObjectPath, ensureObjectParent, ensureUploadRoot, objectKey, removeObject, removeTempFile, uploadRoot } from '../storage.js';
import { financeQuerySchema } from './finance.js';
import { FinanceService } from '../services/finance.js';

const profileSchema = z.object({ contactName: z.string().trim().min(2).max(120), phone: z.string().trim().min(8).max(30), address: z.string().trim().min(5).max(240), city: z.string().trim().min(2).max(80), province: z.string().trim().min(2).max(80), postalCode: z.string().regex(/^\d{5}$/) }).strict();
const submissionSchema = z.object({ name: z.string().trim().min(2).max(120), description: z.string().trim().min(10).max(2000), categoryId: z.string().min(1), hppRupiah: z.number().int().positive().max(2_000_000_000).nullable().optional(), capacityAmount: z.number().int().positive().max(10_000_000).nullable().optional(), capacityUnit: z.string().trim().min(1).max(30).nullable().optional(), capacityPeriod: z.string().trim().min(1).max(30).nullable().optional() }).strict();
const submissionUpdateSchema = submissionSchema.extend({ note: z.string().trim().max(1000).optional() }).strict();
const idSchema = z.string().regex(/^[a-zA-Z0-9_-]{10,}$/);
const documentTypeSchema = z.nativeEnum(LegalDocumentType);
const allowedMimes = new Set(['application/pdf', 'image/jpeg', 'image/png']);
const allowedExtensions = new Set(['.pdf', '.jpg', '.jpeg', '.png']);
const safeOriginalName = (name: string) => path.basename(name).replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 180) || 'upload';
const safeFile = async (file: Express.Multer.File) => { const bytes = await readFile(file.path); if (file.mimetype === 'application/pdf') return bytes.subarray(0, 5).toString() === '%PDF-'; if (file.mimetype === 'image/png') return bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])); if (file.mimetype === 'image/jpeg') return bytes.subarray(0, 3).equals(Buffer.from([255, 216, 255])); return false; };
const upload = multer({
  dest: uploadRoot,
  limits: { fileSize: 8 * 1024 * 1024, files: 1, fields: 12, parts: 14 },
  fileFilter: (_req, file, callback) => callback(null, allowedMimes.has(file.mimetype) && allowedExtensions.has(path.extname(file.originalname).toLowerCase()))
});

const partnerForUser = async (prisma: PrismaClient, userId: string) => prisma.partner.findFirst({ where: { userId } });
const submissionSelect = { id: true, name: true, description: true, categoryId: true, hppRupiah: true, capacityAmount: true, capacityUnit: true, capacityPeriod: true, status: true, submittedAt: true, createdAt: true, updatedAt: true, category: { select: { name: true, slug: true } }, photos: { select: { id: true, originalName: true, mimeType: true, sizeBytes: true, createdAt: true }, orderBy: { createdAt: 'asc' as const } }, revisions: { select: { id: true, fromStatus: true, toStatus: true, note: true, createdAt: true, actor: { select: { id: true, name: true, role: true } } }, orderBy: { createdAt: 'asc' as const } } };
const completeForSubmit = (submission: { name: string; description: string; categoryId: string; hppRupiah: number | null; capacityAmount: number | null; capacityUnit: string | null; capacityPeriod: string | null; photos: unknown[] }) => Boolean(submission.name && submission.description && submission.categoryId && submission.hppRupiah && submission.capacityAmount && submission.capacityUnit && submission.capacityPeriod && submission.photos.length);

export const partnerRouter = (prisma: PrismaClient, auth: AuthService) => {
  const router = Router();
  router.use(authenticate(auth), requireRoles('PARTNER'));
  router.get('/overview', async (req, res, next) => { try { const partner = await partnerForUser(prisma, req.user!.id); if (!partner) throw new HttpError(404, 'Partner not found'); const [drafts, submitted, profile, documents] = await Promise.all([prisma.productSubmission.count({ where: { partnerId: partner.id, status: SubmissionStatus.DRAFT } }), prisma.productSubmission.count({ where: { partnerId: partner.id, status: { not: SubmissionStatus.DRAFT } } }), prisma.partnerProfile.count({ where: { partnerId: partner.id } }), prisma.legalDocument.count({ where: { partnerId: partner.id } })]); res.json({ partner: { id: partner.id, name: partner.name }, counts: { drafts, submitted, profile, documents } }); } catch (error) { next(error); } });
    router.get('/categories', async (_req, res, next) => { try { res.json({ categories: await prisma.category.findMany({ select: { id: true, name: true, slug: true }, orderBy: { name: 'asc' } }) }); } catch (error) { next(error); } });

  router.get('/profile', async (req, res, next) => { try { const partner = await partnerForUser(prisma, req.user!.id); if (!partner) throw new HttpError(404, 'Partner not found'); res.json({ profile: await prisma.partnerProfile.findUnique({ where: { partnerId: partner.id } }) }); } catch (error) { next(error); } });
  router.put('/profile', requireSameOrigin, async (req, res, next) => { try { const values = profileSchema.parse(req.body); const partner = await partnerForUser(prisma, req.user!.id); if (!partner) throw new HttpError(404, 'Partner not found'); const profile = await prisma.partnerProfile.upsert({ where: { partnerId: partner.id }, create: { partnerId: partner.id, ...values }, update: values }); res.json({ profile }); } catch (error) { next(error); } });

  router.get('/legal-documents', async (req, res, next) => { try { const partner = await partnerForUser(prisma, req.user!.id); if (!partner) throw new HttpError(404, 'Partner not found'); const documents = await prisma.legalDocument.findMany({ where: { partnerId: partner.id }, select: { id: true, type: true, status: true, originalName: true, mimeType: true, sizeBytes: true, createdAt: true }, orderBy: { createdAt: 'desc' } }); res.json({ documents }); } catch (error) { next(error); } });
  router.post('/legal-documents', requireSameOrigin, upload.single('file'), async (req, res, next) => { try { const type = documentTypeSchema.parse(req.body.type); const file = req.file; if (!file || !allowedMimes.has(file.mimetype) || !await safeFile(file)) throw new HttpError(400, 'Invalid file'); const partner = await partnerForUser(prisma, req.user!.id); if (!partner) throw new HttpError(404, 'Partner not found'); await ensureUploadRoot(); const key = objectKey(`partners/${partner.id}/legal`, path.extname(file.originalname).toLowerCase()); const target = absoluteObjectPath(key); await ensureObjectParent(key); const { rename } = await import('node:fs/promises'); await rename(file.path, target); const document = await prisma.legalDocument.create({ data: { partnerId: partner.id, type, originalName: safeOriginalName(file.originalname), objectKey: key, mimeType: file.mimetype, sizeBytes: file.size }, select: { id: true, type: true, status: true, originalName: true, mimeType: true, sizeBytes: true, createdAt: true } }); res.status(201).json({ document }); } catch (error) { if (req.file) await removeTempFile(req.file.path).catch(() => undefined); next(error); } });
  router.delete('/legal-documents/:id', requireSameOrigin, async (req, res, next) => { try { const id = idSchema.parse(req.params.id); const partner = await partnerForUser(prisma, req.user!.id); if (!partner) throw new HttpError(404, 'Partner not found'); const document = await prisma.legalDocument.findFirst({ where: { id, partnerId: partner.id } }); if (!document) throw new HttpError(404, 'Document not found'); await prisma.legalDocument.delete({ where: { id: document.id } }); await removeObject(document.objectKey); res.status(204).send(); } catch (error) { next(error); } });

  router.get('/submissions', async (req, res, next) => { try { const partner = await partnerForUser(prisma, req.user!.id); if (!partner) throw new HttpError(404, 'Partner not found'); const submissions = await prisma.productSubmission.findMany({ where: { partnerId: partner.id }, select: { ...submissionSelect, photos: false, revisions: false }, orderBy: { updatedAt: 'desc' } }); res.json({ submissions }); } catch (error) { next(error); } });
  router.post('/submissions', requireSameOrigin, async (req, res, next) => { try { const values = submissionSchema.parse(req.body); const partner = await partnerForUser(prisma, req.user!.id); if (!partner) throw new HttpError(404, 'Partner not found'); const category = await prisma.category.findFirst({ where: { OR: [{ id: values.categoryId }, { slug: values.categoryId }] }, select: { id: true } }); if (!category) throw new HttpError(400, 'Invalid category'); const submission = await prisma.productSubmission.create({ data: { ...values, categoryId: category.id, partnerId: partner.id, hppRupiah: values.hppRupiah ?? null, capacityAmount: values.capacityAmount ?? null, capacityUnit: values.capacityUnit ?? null, capacityPeriod: values.capacityPeriod ?? null }, select: submissionSelect }); res.status(201).json({ submission }); } catch (error) { next(error); } });

  router.get('/finance', async (req, res, next) => { try { const partner = await partnerForUser(prisma, req.user!.id); if (!partner) throw new HttpError(404, 'Partner not found'); const query = financeQuerySchema.parse(req.query); res.json({ finance: await new FinanceService(prisma).partnerFinance(partner.id, { from: query.from, to: query.to }) }); } catch (error) { next(error); } });

  const ownedSubmission = async (req: Parameters<typeof router.get>[1] extends never ? never : any) => { const id = idSchema.parse(req.params.id); return prisma.productSubmission.findFirst({ where: { id, partner: { userId: req.user!.id } }, select: submissionSelect }); };
  router.get('/submissions/:id', async (req, res, next) => { try { const submission = await ownedSubmission(req); if (!submission) throw new HttpError(404, 'Submission not found'); res.json({ submission }); } catch (error) { next(error); } });
  router.patch('/submissions/:id', requireSameOrigin, async (req, res, next) => { try { const parsed = submissionUpdateSchema.parse(req.body); const { note, ...values } = parsed; const current = await ownedSubmission(req); if (!current) throw new HttpError(404, 'Submission not found'); if (current.status !== SubmissionStatus.DRAFT && current.status !== SubmissionStatus.REVISION_REQUIRED) throw new HttpError(409, 'Submission is immutable'); const category = await prisma.category.findFirst({ where: { OR: [{ id: values.categoryId }, { slug: values.categoryId }] }, select: { id: true } }); if (!category) throw new HttpError(400, 'Invalid category'); const submission = await prisma.$transaction(async (tx) => { const updated = await tx.productSubmission.update({ where: { id: current.id }, data: { ...values, categoryId: category.id }, select: submissionSelect }); if (current.status === SubmissionStatus.REVISION_REQUIRED && note) await tx.submissionRevision.create({ data: { submissionId: current.id, actorUserId: req.user!.id, fromStatus: current.status, toStatus: current.status, note } }); return updated; }); res.json({ submission }); } catch (error) { next(error); } });
  router.post('/submissions/:id/photos', requireSameOrigin, upload.single('file'), async (req, res, next) => { try { const current = await ownedSubmission(req); if (!current) throw new HttpError(404, 'Submission not found'); if (current.status !== SubmissionStatus.DRAFT && current.status !== SubmissionStatus.REVISION_REQUIRED) throw new HttpError(409, 'Submission is immutable'); const file = req.file; if (!file || !allowedMimes.has(file.mimetype) || !await safeFile(file)) throw new HttpError(400, 'Invalid file'); const key = objectKey(`submissions/${current.id}/photos`, path.extname(file.originalname).toLowerCase()); await ensureUploadRoot(); await ensureObjectParent(key); await (await import('node:fs/promises')).rename(file.path, absoluteObjectPath(key)); const photo = await prisma.submissionPhoto.create({ data: { submissionId: current.id, originalName: safeOriginalName(file.originalname), objectKey: key, mimeType: file.mimetype, sizeBytes: file.size }, select: { id: true, originalName: true, mimeType: true, sizeBytes: true, createdAt: true } }); res.status(201).json({ photo }); } catch (error) { if (req.file) await removeTempFile(req.file.path).catch(() => undefined); next(error); } });
  router.post('/submissions/:id/submit', requireSameOrigin, async (req, res, next) => { try { const current = await ownedSubmission(req); if (!current) throw new HttpError(404, 'Submission not found'); if (current.status !== SubmissionStatus.DRAFT && current.status !== SubmissionStatus.REVISION_REQUIRED) throw new HttpError(409, 'Submission cannot be submitted'); if (!completeForSubmit(current)) throw new HttpError(400, 'Submission is incomplete'); const submission = await prisma.$transaction(async (tx) => { const updated = await tx.productSubmission.update({ where: { id: current.id }, data: { status: SubmissionStatus.SUBMITTED, submittedAt: new Date() }, select: submissionSelect }); await tx.submissionRevision.create({ data: { submissionId: current.id, actorUserId: req.user!.id, fromStatus: current.status, toStatus: SubmissionStatus.SUBMITTED } }); return updated; }); res.json({ submission }); } catch (error) { next(error); } });
  return router;
};
